# Generated by Django 5.0.6 on 2024-07-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='ratting',
            new_name='rating',
        ),
    ]
