# Generated by Django 5.0.6 on 2024-07-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0002_rename_ratting_booklist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
