# Generated by Django 5.0.6 on 2024-07-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_address_author_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='booklist',
            name='published_country',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
