# Generated by Django 5.0.6 on 2024-07-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_alter_country_options_alter_country_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True, 'verbose_name': 'author_country', 'verbose_name_plural': 'Country of the Authors'},
        ),
        migrations.AlterModelTable(
            name='country',
            table='author_country',
        ),
    ]
